
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ouma-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ouma
  template:
    metadata:
      labels:
        app: ouma
    spec:
      containers:
        - name: ouma
          image: ouma:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: INFLUX_DB_BUCKET
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: INFLUX_DB_BUCKET
            - name: INFLUX_DB_ORG
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: INFLUX_DB_ORG
            - name: INFLUX_DB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: INFLUX_DB_TOKEN
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: MYSQL_DB
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: SECRET_KEY
            - name: TARGET_SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: TARGET_SERVER_PORT
            - name: PREDICTION_INTERVAL
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: PREDICTION_INTERVAL
            - name: ACTIVATE_EMAIL_ALERTING
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: ACTIVATE_EMAIL_ALERTING
            - name: ACTIVATE_SLACK_ALERTING
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: ACTIVATE_SLACK_ALERTING
            - name: SYSTEM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: SYSTEM_EMAIL
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: SMTP_SERVER
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: SMTP_PORT
            - name: SYSTEM_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: SYSTEM_EMAIL_PASSWORD
            - name: SYSTEM_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: SYSTEM_EMAIL_PASSWORD
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: SLACK_TOKEN
            - name: SLACK_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: SLACK_CHANNEL
            - name: SLACK_USER
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: SLACK_USER
            - name: TARGET_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: TARGET_SERVER_HOST
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: MYSQL_HOST
            - name: INFLUX_DB_URL
              valueFrom:
                secretKeyRef:
                  name: ouma-secret
                  key: INFLUX_DB_URL
            
            